[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "aceflow"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3",
]

[tool.maturin]
# This points to the Rust crate in the `aceflow_core` subdirectory
manifest-path = "aceflow_core/Cargo.toml"
# This tells Maturin where the compiled module should go in the Python package
module-name = "aceflow.aceflow_core"
# This specifies we are using PyO3 for the bindings
bindings = "pyo3"